import jsPDF from 'jspdf';
import 'jspdf-autotable';
import html2canvas from 'html2canvas';

/**
 * Generate a PDF from the timetable DOM element
 * @param {HTMLElement} timetableElement - The DOM element containing the timetable
 * @param {string} fileName - The name for the downloaded file
 */
export const generateTimetablePDF = async (timetableElement, fileName = 'timetable.pdf') => {
  try {
    // Create a new PDF document
    const pdf = new jsPDF('l', 'mm', 'a4');
    
    // Check if element exists
    if (!timetableElement) {
      console.error('Timetable element not found');
      alert('Could not generate PDF. Timetable not found.');
      return;
    }
    
    // Capture the timetable as an image
    console.log('Capturing timetable...');
    const canvas = await html2canvas(timetableElement, {
      scale: 2,
      useCORS: true,
      logging: false
    });
    
    const imgData = canvas.toDataURL('image/png');
    
    // Add title
    pdf.setFontSize(18);
    pdf.text('Academic Timetable', 20, 20);
    
    // Add the image to the PDF
    const imgWidth = pdf.internal.pageSize.getWidth() - 40;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;
    
    pdf.addImage(imgData, 'PNG', 20, 30, imgWidth, imgHeight);
    
    // Add footer
    pdf.setFontSize(10);
    pdf.setTextColor(100, 100, 100);
    pdf.text('Generated by Academic Scheduler', 20, pdf.internal.pageSize.getHeight() - 10);
    
    // Save the PDF
    pdf.save(fileName);
    console.log('PDF saved as', fileName);
    
  } catch (error) {
    console.error('Error generating PDF:', error);
    alert('Error generating PDF. Please try again.');
  }
};

export default { 
  generateTimetablePDF 
};
